In [1]:
import numpy as np
from utils import factor_model_solution, open_closed_data

In [7]:
X = open_closed_data()
print(X.shape)

np.corrcoef(X.T).round(3)

(88, 5)


array([[1.   , 0.553, 0.547, 0.409, 0.389],
       [0.553, 1.   , 0.61 , 0.485, 0.436],
       [0.547, 0.61 , 1.   , 0.711, 0.665],
       [0.409, 0.485, 0.711, 1.   , 0.607],
       [0.389, 0.436, 0.665, 0.607, 1.   ]])

Only $cov(x_1, x_4)$ is different by a margin.

|    1  |   2   |   3   |   4   |   5   | 
|  ---  |  ---  |  ---  |  ---  |  ---  |
|   1   | 0.553 | 0.547 | 0.410 | 0.389 |
|       |  1    | 0.610 | 0.485 | 0.437 |
|       |       |   1   | 0.711 | 0.665 |
|       |       |       |   1   | 0.607 |
|       |       |       |       |   1   |

In [3]:
psi_hat, lambda_hat = factor_model_solution(X, k=2, standardized=False)
lambda_hat.round(3)

array([[-12.411, -11.32 ],
       [ -9.499,  -3.822],
       [ -9.541,   0.683],
       [-12.246,   4.082],
       [-13.941,   6.541]])

Not even close to what they get. Something is wrong. Let's use the correlation matrix instead. "Thus (9.2.12) is
satisfied. and the m.l.e.s for the parameters of the standardized variables can be found by replacing S by R in (9.4.1)" (Page 263)

In [4]:
psi_hat, lambda_hat = factor_model_solution(X, k=2, standardized=True)
print(repr(psi_hat))
lambda_hat.round(3)

array([[0.465884  , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.41905738, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.18856904, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.35179317, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.43102915]])


array([[-0.628, -0.373],
       [-0.695, -0.312],
       [-0.899,  0.05 ],
       [-0.78 ,  0.201],
       [-0.727,  0.2  ]])

Using correlation matrix (standardized variables), gives the correct results. (the sign of the second eigenvector might be different; this is still a valid eigenvector for that eigenvalue)