In [1]:
import numpy as np
import pandas as pd

from utils import factor_model_solution, factor_model_solution_correlation_matrix, open_closed_data

In [2]:
corr_matrix = np.zeros((15, 15))

correlation_data = np.array([[1.00, 0.24, 0.04, 0.31, 0.09, 0.23, -0.11, 0.27, 0.55, 0.35, 0.28, 0.34, 0.37, 0.47, 0.59],
            [1.00, 0.12, 0.38, 0.43, 0.37, 0.35, 0.48, 0.14, 0.34, 0.55, 0.51, 0.51, 0.28, 0.38],
            [1.00, 0.00, 0.00, 0.08, -0.03, 0.05, 0.27, 0.09, 0.04, 0.20, 0.29, -0.32, 0.14],
            [1.00, 0.3, 0.48, 0.65, 0.35, 0.14, 0.39, 0.35, 0.5, 0.61, 0.69, 0.33],
            [1.00, 0.81, 0.41, 0.82, 0.02, 0.70, 0.84, 0.72, 0.67, 0.48, 0.25],
            [1.00, 0.36, 0.83, 0.15, 0.70, 0.76, 0.88, 0.78, 0.53, 0.42],
            [1.00, 0.23, -0.16, 0.28, 0.21, 0.39, 0.42, 0.45, 0.00],
            [1.00, 0.23, 0.81, 0.86, 0.77, 0.73, 0.55, 0.55],
            [1.00, 0.34, 0.20, 0.30, 0.35, 0.21, 0.69],
            [1.00, 0.78, 0.71, 0.79, 0.61, 0.62],
            [1.00, 0.78, 0.77, 0.55, 0.43],
            [1.00, 0.88, 0.55, 0.53],
            [1.00, 0.54, 0.57],
            [1.00, 0.40],
            [1]], dtype = "object")

for i in range(15):
    corr_matrix[i, i:] = correlation_data[i]

lower_indices = np.tril_indices(15, -1)
corr_matrix[lower_indices] = corr_matrix.T[lower_indices]
corr_matrix




array([[ 1.  ,  0.24,  0.04,  0.31,  0.09,  0.23, -0.11,  0.27,  0.55,
         0.35,  0.28,  0.34,  0.37,  0.47,  0.59],
       [ 0.24,  1.  ,  0.12,  0.38,  0.43,  0.37,  0.35,  0.48,  0.14,
         0.34,  0.55,  0.51,  0.51,  0.28,  0.38],
       [ 0.04,  0.12,  1.  ,  0.  ,  0.  ,  0.08, -0.03,  0.05,  0.27,
         0.09,  0.04,  0.2 ,  0.29, -0.32,  0.14],
       [ 0.31,  0.38,  0.  ,  1.  ,  0.3 ,  0.48,  0.65,  0.35,  0.14,
         0.39,  0.35,  0.5 ,  0.61,  0.69,  0.33],
       [ 0.09,  0.43,  0.  ,  0.3 ,  1.  ,  0.81,  0.41,  0.82,  0.02,
         0.7 ,  0.84,  0.72,  0.67,  0.48,  0.25],
       [ 0.23,  0.37,  0.08,  0.48,  0.81,  1.  ,  0.36,  0.83,  0.15,
         0.7 ,  0.76,  0.88,  0.78,  0.53,  0.42],
       [-0.11,  0.35, -0.03,  0.65,  0.41,  0.36,  1.  ,  0.23, -0.16,
         0.28,  0.21,  0.39,  0.42,  0.45,  0.  ],
       [ 0.27,  0.48,  0.05,  0.35,  0.82,  0.83,  0.23,  1.  ,  0.23,
         0.81,  0.86,  0.77,  0.73,  0.55,  0.55],
       [ 0.55,  0.14,  0

In [3]:
data = open_closed_data().T

factor_model_solution_correlation_matrix(np.corrcoef(data), k=2)

(array([[0.465884  , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 0.41905738, 0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.18856904, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.35179317, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.43102915]]),
 array([[-0.62839619, -0.37313711],
        [-0.69537668, -0.31207659],
        [-0.89940809,  0.04996177],
        [-0.77960162,  0.20106861],
        [-0.72734245,  0.19986738]]))

In [4]:
factor_model_solution_correlation_matrix(corr_matrix, 7)

(array([[4.38858721e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 3.07043805e-01, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 5.40153806e-01, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.23736944e-01,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00

In [37]:

def varimax_rotation(lambda_):

    # need to make some assert here as it only "works"
    # for k==2
    h = np.sqrt((lambda_ ** 2).sum(axis=1))
    #assert for that no entrace should be 0
    d = lambda_ / h[:, np.newaxis]

    g40 = (d[:, 0] ** 4).sum()
    g04 = (d[:, 1] ** 4).sum()

    g22 = (d[:, 0] ** 2 * d[:, 1] ** 2).sum()
    g11 = (d[:, 0] * d[:, 1]).sum()

    g31 = (d[:, 0] ** 3 * d[:, 1]).sum()
    g13 = (d[:, 0] * d[:, 1] ** 3).sum()

    g20 = (d[:, 0] ** 2).sum()
    g02 = (d[:, 1] ** 2).sum()
    
    A = (g04 + g40 - 6 * g22 - g02 ** 2 - g20 ** 2 + 2 * g02 * g20 + 4 * g11 ** 2)
    B = 4 * (g13 - g31 - g11 * g02 + g11 * g20)
    
    alpha = np.arctan2(B, A)
    theta_radianer = alpha / 4
    theta_grader = np.degrees(theta_radianer) 
    
    G = np.array([[np.cos(theta_radianer), np.sin(theta_radianer)],
              [-np.sin(theta_radianer), np.cos(theta_radianer)]])

    
    delta = lambda_.dot(G)
    
    return delta, theta_grader, G

In [40]:
lambda_original = np.array([[0.628, 0.372],
                    [0.696,  0.313],
                    [0.899,  -0.05 ],
                    [0.779,  -0.201],
                    [0.728,  -0.2  ]])

lambda_rotated, theta_grader, G_matrix = varimax_rotation(lambda_original)

lambda_rotated_2, theta_grader_2, G_matrix_2 = varimax_rotation(lambda_rotated)

print(theta_grader)
print(G_matrix)
print(lambda_rotated)

print(lambda_rotated_2, theta_grader_2, G_matrix_2)



40.714055418940575
[[ 0.75797434  0.65228436]
 [-0.65228436  0.75797434]]
[[0.2333581  0.69160104]
 [0.32338514 0.69123589]
 [0.71403315 0.54850493]
 [0.72157117 0.35577668]
 [0.6822622  0.32326815]]
[[0.2333581  0.69160104]
 [0.32338514 0.69123589]
 [0.71403315 0.54850493]
 [0.72157117 0.35577668]
 [0.6822622  0.32326815]] 3.6288360242380905e-15 [[ 1.00000000e+00  6.33351366e-17]
 [-6.33351366e-17  1.00000000e+00]]
